############## Detec_type CONFIG ##################

#Use this file to give your inputs

#Insert the name of the database for the samples you want to analyse (example: influenza).
#If is the first time using this databse you need to add the path to the fasta file contining the database, a new database will be created with the name of the given fasta file (example: path/to/my_database.fasta).
database:
  "path/to/my_database.fasta"


#Insert the path to the folder with the samples you wish to analyse (example:path/to/my_samples_folder/). 
#This folder can contain samples from different technologies, as long as they are all analyzed according to the same database.
sample_directory:
  "path/to/my_samples_folder/"
  

#Chose the name of your final csv output file (default="all_samples"), and a directory for your results (default="results").
output_name:
  "all_samples"


output_directory:
  "results/"


#Opcionally, especify the tecnologies you are going to analyse (default="any"). If you leave it with the default, all samples of the given folder will be analysed.
#Your opcions are: 'fasta', 'nanopore','illumina_single','illumina_paired','sanger','any'.
tecnology:
- any


# If you are going to analyse any multi-fasta files, give a list with the name of each multi-fasta file (default="none"). You can chosse "all" if all of your fasta files are multi-fasta.
multi_fasta:
- none


#Now you can change some params for your analysis
#Choose how many threads you which to use (default=2).
threads:
  2


#Abricate params
#Minimum DNA %identity (default=1).
minid:
  1

#Minimum DNA %coverage (default=1).
mincov:
  1

#Sanger params
#Abiview params: First base to report or display (default=20).
startbase:
  20

#Abiview params: Last sequence base to report or display (default=800).
endbase:
  800

