############## ReportType config ##################



#Use this file to configure your analysis

#Insert the name of the database for the samples you want to analyse (example: database=my_database).
#If is the first time using this databse you need to add the complete path to the fasta file (seq~~~id~~~acession) contaning the database.
#Every time you enter the complete path, a new database will be created with the name of your fasta file
database:
  "path/to/my_database.fasta"
  
#If you don't have a fasta file already formatted for Abricate (seq~~~gene~~~acession), you can provide a fasta file containing only sequences and a table (tsv) with three columns, first one (sequence) for sequence name, second (id) for corresponding element, such as genotype, subspecies, type, and third (accession) for the accession of each sequence.
#Specify the name of your new database in the "database" variable.
#Note that you should not alter the following parameters if you already have a formatted fasta file.
fasta_db:
  "path/to/sequences.fasta"
  
table_db:
  "path/to/table.tsv"


#Insert the path to the folder with the samples you wish to analyse (example:path/to/my_samples_folder/). 
#This folder can contain samples from different technologies, as long as they are all analyzed according to the same database.
sample_directory:
  "path/to/my_samples_folder/"
  
#If you wish to analyse only one sample you must give the sample name, you can provide a list of samples (default=all). Note that in paired end sequences, you must give the sample name without any prefixes.
sample_name:
  "all"
  
#Choose the name of your final csv output file (default="all_samples"), and a directory for your results (default="results").
output_name:
  "all_samples"


output_directory:
  "results"


#Opcionally, especify the input format you are going to analyse (default="any"). If you leave it with the default, all samples of the given folder will be analysed.
#Your options are: 'fasta', 'nanopore','illumina_single','illumina_paired','sanger','any'.
input_format:
  "any"


# If you are going to analyse any multi-fasta files, give a list with the name of each multi-fasta file (default="none"). You can chosse "all" if all of your fasta files are multi-fasta.
multi_fasta:
  "none"


#Choose how many threads you which to use (default=2).
threads:
  2

#At last, you can choose if, in case there is more than one gene detected, you want to prioritize greater coverage or greater identity (default:"cov")
#Your options are: 'cov', 'id'
prioritize:
  "cov" 

#Abricate paramsv
#Minimum DNA %identity (default=1).
minid:
  1

#Minimum DNA %coverage (default=1).
mincov:
  1

#Illumina cleaning params (you can chosse deferently for single and paired reads)
#Trimmomatic Illuminaclip: enter the directory of your illumina adapters, as well as specific cleaning informations for your file (default: "ILLUMINACLIP:primers/adapters.fasta:3:30:10:6:true") 
illuminaclip_single:
  "ILLUMINACLIP:primers/adapters.fasta:3:30:10:6:true"
  
illuminaclip_paired:
  "ILLUMINACLIP:primers/adapters.fasta:3:30:10:6:true"
  
#Trimmomatic Slidingwindow: minimum average quality established for each sequence according to a certain number of bases (default="SLIDINGWINDOW:5:20").
slidingwindow_single:
  "SLIDINGWINDOW:5:20"
  
slidingwindow_paired:
  "SLIDINGWINDOW:5:20"
  
#Trimmomatic Minlen: minimum read size (default="MINLEN:36").
minlen_single:
  "MINLEN:36"

minlen_paired:
  "MINLEN:36"
  
#Trimmomatic Leading: bases to remove at the beginning of the read (default="LEADING:3")
leading_single:
  "LEADING:3"
  
leading_paired:
  "LEADING:3"
  
#Trimmomatic Trailing: bases to remove at the end of the read (default="TRAILING:3")
trailing_single:
  "TRAILING:3"

trailing_paired:
  "TRAILING:3"

#Trimmomatic encoding: if quality encoding is not specified in fastq file, specify the quality encoding (default=in_file)
#Your options are 'phred33', 'phred64', 'in_file'
encoding_single: 
  "in_file"

encoding_paired:
  "in_file"

#Nanopore params
#Nanofilt minimum quality: minimum quality mean for read (default=8).
quality:
  8

#Nanofilt length: minimum length per read (default=50)
length:
  50
  
#Nanofilt maxlength: maximum length per read (default=50000)
maxlength:
  50000

#Nanofilt headcrop: bases to remove at the beginning of the read (default=30)
headcrop:
  30
  
#Nanofilt tailcrop: bases to remove at the end of the read (default=30)
tailcrop:
  30 

#Raven k-mer: length of minimizers used to find overlaps (default=15)
kmer:
  15
  
#Raven polishing-rounds: number of times racon is invoked (default=2)
polishing:
  2
  
  

#Sanger params
#Abiview params: First base to report or display (default=20).
startbase:
  20

#Abiview params: Last sequence base to report or display (default=800).
endbase:
  800




